### ISSUE TITLE
Add mfcc

### ISSUE THREAD

**Issue by r9y9** [r9y9/SPTK.jl#9]

**Comment by WojciechMigda** [comment]
The comment
`# Please note that mfcc is NOT stable`
appplies to the julia code of the `mfcc` function or to the wrapped SPTK implementation? What stability is referred to, numerical, runtime, etc.?

**Comment by r9y9** [comment]
https://github.com/r9y9/SPTK.jl/blob/master/test/mfcc.jl#L39-L48 tests were irregularly failing in travis and my local environment. I guess there might be a memory corruption bug in SPTK.

When I experimented with mfcc previously, calling mfcc mutlple-times sometimes causes NaN even if the same input is used.

**Comment by WojciechMigda** [comment]
Thank you for the clarification.

**Comment by r9y9** [comment]
https://sourceforge.net/p/sp-tk/bugs/94/ heap-overflow bug is now fixed in my fork.
